
package view;

import SistemaBancario.ContaCorrente;
import SistemaBancario.ContaEspecial;
import SistemaBancario.Pessoa;
import Utilit.Util;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Alinda
 */
public class SisBank extends javax.swing.JFrame {

    private final int CONTA_ABERTA = 1;
    private final int CONTA_FECHADA = 0;
    private ContaCorrente conta;

    public SisBank() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGTipoConta = new javax.swing.ButtonGroup();
        jPDados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFTFNumeroConta = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFNomeTitular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFSobrenomeTitular = new javax.swing.JTextField();
        jFTFCpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRBContaSimples = new javax.swing.JRadioButton();
        jRBContaEspecial = new javax.swing.JRadioButton();
        jPOperacoes = new javax.swing.JPanel();
        jBAberturaConta = new javax.swing.JButton();
        jBDepositar = new javax.swing.JButton();
        jBSacar = new javax.swing.JButton();
        jBLimparCampos = new javax.swing.JButton();
        jPInformacoes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAInformacoes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Bancário - versão 1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados:"));

        jLabel1.setText("Número da Conta:");

        try {
            jFTFNumeroConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFNumeroConta.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFTFNumeroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFNumeroContaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do Titular:");

        jLabel3.setText("Sobrenome do Titular:");

        try {
            jFTFCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCpf.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        jLabel4.setText("CPF do Titular:");

        jLabel5.setText("Tipo da Conta:");

        bGTipoConta.add(jRBContaSimples);
        jRBContaSimples.setText("Simples");

        bGTipoConta.add(jRBContaEspecial);
        jRBContaEspecial.setText("Especial");

        javax.swing.GroupLayout jPDadosLayout = new javax.swing.GroupLayout(jPDados);
        jPDados.setLayout(jPDadosLayout);
        jPDadosLayout.setHorizontalGroup(
            jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNomeTitular)
                    .addComponent(jTFSobrenomeTitular)
                    .addGroup(jPDadosLayout.createSequentialGroup()
                        .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDadosLayout.createSequentialGroup()
                                .addComponent(jRBContaSimples)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRBContaEspecial))
                            .addComponent(jFTFNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPDadosLayout.setVerticalGroup(
            jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPDadosLayout.createSequentialGroup()
                        .addComponent(jFTFNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFNomeTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFSobrenomeTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBContaSimples)
                            .addComponent(jLabel5)
                            .addComponent(jRBContaEspecial))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPOperacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações:"));

        jBAberturaConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add_user.png"))); // NOI18N
        jBAberturaConta.setText("Abertura de Conta:");
        jBAberturaConta.setToolTipText("Efetiva a abertura da conta do cliente");
        jBAberturaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAberturaContaActionPerformed(evt);
            }
        });

        jBDepositar.setText("Depositar");
        jBDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDepositarActionPerformed(evt);
            }
        });

        jBSacar.setText("Sacar");
        jBSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSacarActionPerformed(evt);
            }
        });

        jBLimparCampos.setText("Limpar Campos");
        jBLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOperacoesLayout = new javax.swing.GroupLayout(jPOperacoes);
        jPOperacoes.setLayout(jPOperacoesLayout);
        jPOperacoesLayout.setHorizontalGroup(
            jPOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAberturaConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBDepositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBLimparCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPOperacoesLayout.setVerticalGroup(
            jPOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBAberturaConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDepositar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSacar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBLimparCampos)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPOperacoesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBAberturaConta, jBDepositar, jBLimparCampos, jBSacar});

        jPInformacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações:"));

        jTAInformacoes.setEditable(false);
        jTAInformacoes.setColumns(20);
        jTAInformacoes.setRows(5);
        jScrollPane1.setViewportView(jTAInformacoes);

        javax.swing.GroupLayout jPInformacoesLayout = new javax.swing.GroupLayout(jPInformacoes);
        jPInformacoes.setLayout(jPInformacoesLayout);
        jPInformacoesLayout.setHorizontalGroup(
            jPInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPInformacoesLayout.setVerticalGroup(
            jPInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setEstado(0);
    }//GEN-LAST:event_formWindowOpened

    private void jBAberturaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAberturaContaActionPerformed
        LocalDate dataAbertura = LocalDate.now();

        if (Util.removeMascara(jFTFNumeroConta.getText().trim()).isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Preencha o Nº da CONTA!!!!",
                    "Sistema Bancário",
                    JOptionPane.ERROR_MESSAGE);
            jFTFNumeroConta.requestFocusInWindow();
            return;
        }

        if (jTFNomeTitular.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Preencha o NOME do titular da conta!!!!",
                    "Sistema Bancário",
                    JOptionPane.ERROR_MESSAGE);
            jTFNomeTitular.requestFocus();
            return;
        }
        if (jTFSobrenomeTitular.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Preencha o SOBRENOME do titular da conta!!!!",
                    "Sistema Bancário",
                    JOptionPane.ERROR_MESSAGE);
            jTFSobrenomeTitular.requestFocus();
            return;
        }

        if (Util.removeMascara(jFTFCpf.getText()).trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Preencha o CPF do titular da conta!!!!",
                    "Sistema Bancário",
                    JOptionPane.ERROR_MESSAGE);
            jFTFCpf.requestFocusInWindow();
            return;
        }

        if (bGTipoConta.getSelection() != null) {
            if (jRBContaSimples.isSelected()) {
                conta = new ContaCorrente(jFTFNumeroConta.getText(), new Pessoa(jTFNomeTitular.getText(), jTFSobrenomeTitular.getText(), jFTFCpf.getText()), dataAbertura);
            } else if (jRBContaEspecial.isSelected()) {
                conta = new ContaEspecial(jFTFNumeroConta.getText(), new Pessoa(jTFNomeTitular.getText(), jTFSobrenomeTitular.getText(), jFTFCpf.getText()), dataAbertura);
            }

            jTAInformacoes.setText(conta.toString());
            JOptionPane.showMessageDialog(this, "Abertura de Conta realzada com sucesso!!!!", "Sistema Bancário", 1);
            setEstado(1);
        } else {
            JOptionPane.showMessageDialog(this, "Please, selecione o tipo da conta!", "Aviso", 0);
        }
    }//GEN-LAST:event_jBAberturaContaActionPerformed

    private void jBSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSacarActionPerformed
        double valorSaque = Double.parseDouble(JOptionPane.showInputDialog(null, "Informe o valor a ser sacado", "Sistema Bancário", 3));

        if (conta.sacar(valorSaque) == false){
            JOptionPane.showMessageDialog(this, "SALDO INSUFICIENTE", "Sistema Bancário", 0);
        } else {
            JOptionPane.showMessageDialog(this, "SAQUE REALIZADO COM SUCESSO", "Sistema Bancário", 1);
            jTAInformacoes.setText(conta.toString());

        }
    }//GEN-LAST:event_jBSacarActionPerformed

    private void jBDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDepositarActionPerformed
      
        double valorDeposito = Double.parseDouble(JOptionPane.showInputDialog(this, "Informe o valor que deseja depositar", 
                                                                                                              "Sistema Bancário - Operação DEPÓSITO", 1));

        if (valorDeposito < 0){
             JOptionPane.showMessageDialog(this, "Valor inválido!", "Sistema Bancário", 0);
             return;
        }
        
        conta.depositar(valorDeposito);

        JOptionPane.showMessageDialog(this, "DEPÓSITO REALIZADO COM SUCESSO", "Sistema Bancário", 1);

        jTAInformacoes.setText(conta.toString());

   

    }//GEN-LAST:event_jBDepositarActionPerformed

    private void jBLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparCamposActionPerformed
        jFTFNumeroConta.setText("");
        jTFNomeTitular.setText("");
        jTFSobrenomeTitular.setText("");
        jFTFCpf.setText("");
        jTAInformacoes.setText(null);
        bGTipoConta.clearSelection();
        setEstado(0);
        jFTFNumeroConta.requestFocusInWindow();
    }//GEN-LAST:event_jBLimparCamposActionPerformed

    private void jFTFNumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFNumeroContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFNumeroContaActionPerformed

    private void setEstado(int estado) {
        if (estado == CONTA_ABERTA) {
            jBAberturaConta.setEnabled(false);
            jBDepositar.setEnabled(true);
            jBSacar.setEnabled(true);
            jBLimparCampos.setEnabled(true);
        } else if (estado == CONTA_FECHADA) {
            jBAberturaConta.setEnabled(true);
            jBDepositar.setEnabled(false);
            jBSacar.setEnabled(false);
            jBLimparCampos.setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SisBank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGTipoConta;
    private javax.swing.JButton jBAberturaConta;
    private javax.swing.JButton jBDepositar;
    private javax.swing.JButton jBLimparCampos;
    private javax.swing.JButton jBSacar;
    private javax.swing.JFormattedTextField jFTFCpf;
    private javax.swing.JFormattedTextField jFTFNumeroConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPDados;
    private javax.swing.JPanel jPInformacoes;
    private javax.swing.JPanel jPOperacoes;
    private javax.swing.JRadioButton jRBContaEspecial;
    private javax.swing.JRadioButton jRBContaSimples;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAInformacoes;
    private javax.swing.JTextField jTFNomeTitular;
    private javax.swing.JTextField jTFSobrenomeTitular;
    // End of variables declaration//GEN-END:variables
}
